# backend/app/repositories/interfaces/channel_repo.py
from __future__ import annotations
from typing import Protocol, Optional, Dict, List

class ChannelRepo(Protocol):
    def create_channel(self) -> Dict: ...  # channel_id 파라미터 제거
    def get_channel(self, channel_id: str) -> Optional[Dict]: ...
    def delete_channel(self, channel_id: str) -> bool: ...
    def list_channels(self, limit: int = 50, offset: int = 0) -> List[Dict]: ...
    def delete_sessions_by_channel(self, channel_id: str) -> int: ... 